import { API_KEY_PLACEHOLDER, PUBLIC_BASE_URL } from '@/lib/constants';

const RESPONSE_EXAMPLE = `{
  "ok": true,
  "jobId": "<uuid generated by server>",
  "referenceId": "ORD-20260505-001"
}`;

// Array-composition example — build markup line-by-line from data, join with \n.
// Useful when looping over order items or other dynamic content.
const ARRAY_COMPOSE_JS = `// JavaScript / TypeScript / Node / n8n / Make
const items = [
  { name: "ผัดไทย",  qty: 2, price: 240.00 },
  { name: "ต้มยำ",   qty: 1, price:  80.00 },
];
const total = items.reduce((s, i) => s + i.price, 0);

const lines = [
  "[align: centre][mag: w 2; h 2]ใบเสร็จ[mag]",
  "",
  "[align: left]",
  ...items.map(i =>
    \`[column: left: \${i.name} ×\${i.qty}; right: \${i.price.toFixed(2)}]\`
  ),
  "",
  \`[align: right][bold]TOTAL \${total.toFixed(2)}[/bold]\`,
  "[feed: lines 2]",
  "[cut]",
];

const markup = lines.join("\\n");   // <-- join เป็น string เดียวก่อนส่ง

await fetch("${PUBLIC_BASE_URL}/api/print/jobs", {
  method: "POST",
  headers: {
    "x-api-key": "${API_KEY_PLACEHOLDER}",
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    printerId: "<printer-uuid>",
    referenceId: "ORD-20260505-001",
    markup,
  }),
});`;

const ARRAY_COMPOSE_DELUGE = `// Zoho Deluge
items = List();
items.add({"name": "ผัดไทย", "qty": 2, "price": 240.00});
items.add({"name": "ต้มยำ",  "qty": 1, "price":  80.00});

total = 0.0;
lines = List();
lines.add("[align: centre][mag: w 2; h 2]ใบเสร็จ[mag]");
lines.add("");
lines.add("[align: left]");
for each item in items
{
    line = "[column: left: " + item.get("name") + " ×" + item.get("qty")
         + "; right: " + item.get("price").toString("0.00") + "]";
    lines.add(line);
    total = total + item.get("price");
}
lines.add("");
lines.add("[align: right][bold]TOTAL " + total.toString("0.00") + "[/bold]");
lines.add("[feed: lines 2]");
lines.add("[cut]");

markup = lines.toString("\\n");   // <-- join List เป็น string เดียว

body_map = Map();
body_map.put("printerId", "<printer-uuid>");
body_map.put("referenceId", "ORD-20260505-001");
body_map.put("markup", markup);

header_map = Map();
header_map.put("x-api-key", "${API_KEY_PLACEHOLDER}");
header_map.put("Content-Type", "application/json");

response = invokeurl
[
    url     : "${PUBLIC_BASE_URL}/api/print/jobs"
    type    : POST
    headers : header_map
    parameters   : body_map.toString()
    content-type : "application/json"
];`;

export function ApiSpec({ printerId }: { printerId: string }) {
  const sampleBody = JSON.stringify(
    {
      printerId,
      referenceId: 'ORD-20260505-001',
      markup: '[align: centre]Hello\n[cut]',
    },
    null,
    2,
  );

  const curl = [
    `curl -X POST '${PUBLIC_BASE_URL}/api/print/jobs' \\`,
    `  -H 'x-api-key: ${API_KEY_PLACEHOLDER}' \\`,
    `  -H 'Content-Type: application/json' \\`,
    `  -d '${sampleBody}'`,
  ].join('\n');

  return (
    <section className="rounded-lg border border-gray-200 bg-white p-6">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500">
        API spec
      </h2>
      <p className="mt-1 text-sm text-gray-500">
        วิธีเรียกจากระบบภายนอก (Zoho, Make, n8n, ฯลฯ) — แทน{' '}
        <code className="rounded bg-gray-100 px-1">{API_KEY_PLACEHOLDER}</code>{' '}
        ด้วย secret ที่ WidelyNext แจ้ง
      </p>

      <dl className="mt-4 grid grid-cols-[max-content_1fr] gap-x-4 gap-y-2 text-sm">
        <dt className="font-medium text-gray-700">Endpoint</dt>
        <dd className="font-mono text-xs">
          POST {PUBLIC_BASE_URL}/api/print/jobs
        </dd>

        <dt className="font-medium text-gray-700">Headers</dt>
        <dd className="font-mono text-xs">
          x-api-key: {API_KEY_PLACEHOLDER}
          <br />
          Content-Type: application/json
        </dd>

        <dt className="self-start pt-1 font-medium text-gray-700">Body</dt>
        <dd>
          <pre className="overflow-x-auto rounded bg-gray-50 p-3 font-mono text-xs leading-5">
{sampleBody}
          </pre>
          <ul className="mt-2 space-y-1 text-xs text-gray-500">
            <li>
              <code className="rounded bg-gray-100 px-1">printerId</code>{' '}
              <span className="text-red-500">required</span> — UUID จากตาราง
              printer ในระบบ
            </li>
            <li>
              <code className="rounded bg-gray-100 px-1">referenceId</code>{' '}
              optional — รหัสอ้างอิงฝั่งคุณ ส่งซ้ำได้ (ไม่ dedup)
            </li>
            <li>
              <code className="rounded bg-gray-100 px-1">markup</code>{' '}
              <span className="text-red-500">required</span> — Star Document
              Markup
            </li>
          </ul>
        </dd>

        <dt className="self-start pt-1 font-medium text-gray-700">Response</dt>
        <dd>
          <pre className="overflow-x-auto rounded bg-gray-50 p-3 font-mono text-xs leading-5">
{RESPONSE_EXAMPLE}
          </pre>
        </dd>

        <dt className="self-start pt-1 font-medium text-gray-700">cURL</dt>
        <dd>
          <pre className="overflow-x-auto rounded bg-gray-50 p-3 font-mono text-xs leading-5">
{curl}
          </pre>
        </dd>
      </dl>

      <div className="mt-6 border-t border-gray-200 pt-5">
        <h3 className="text-sm font-semibold text-gray-700">
          ประกอบ markup จาก array
        </h3>
        <p className="mt-1 text-xs text-gray-500">
          ถ้าเนื้อหาใบเสร็จมาจาก list (รายการอาหาร, ผู้โดยสาร, ฯลฯ) ให้สร้างเป็น
          array ของบรรทัดก่อน แล้ว <code className="rounded bg-gray-100 px-1">join</code>{' '}
          ด้วย <code className="rounded bg-gray-100 px-1">\n</code> ก่อนส่ง — field{' '}
          <code className="rounded bg-gray-100 px-1">markup</code> ของ API
          ต้องเป็น string เดียวเสมอ
        </p>

        <div className="mt-3 grid gap-3 lg:grid-cols-2">
          <div>
            <div className="mb-1 text-xs font-medium text-gray-600">
              JavaScript / TypeScript
            </div>
            <pre className="overflow-x-auto rounded bg-gray-50 p-3 font-mono text-xs leading-5">
{ARRAY_COMPOSE_JS}
            </pre>
          </div>
          <div>
            <div className="mb-1 text-xs font-medium text-gray-600">
              Zoho Deluge
            </div>
            <pre className="overflow-x-auto rounded bg-gray-50 p-3 font-mono text-xs leading-5">
{ARRAY_COMPOSE_DELUGE}
            </pre>
          </div>
        </div>
      </div>

      <p className="mt-4 text-xs text-gray-500">
        เอกสารฉบับเต็ม: ดู{' '}
        <code className="rounded bg-gray-100 px-1">_documents/API.md</code>
      </p>
    </section>
  );
}
