import { API_KEY_PLACEHOLDER, PUBLIC_BASE_URL } from '@/lib/constants';

const RESPONSE_EXAMPLE = `{
  "ok": true,
  "jobId": "<uuid generated by server>",
  "referenceId": "ORD-20260505-001"
}`;

export function ApiSpec({ printerId }: { printerId: string }) {
  const sampleBody = JSON.stringify(
    {
      printerId,
      referenceId: 'ORD-20260505-001',
      markup: '[align: centre]Hello\n[cut]',
    },
    null,
    2,
  );

  const curl = [
    `curl -X POST '${PUBLIC_BASE_URL}/api/print/jobs' \\`,
    `  -H 'x-api-key: ${API_KEY_PLACEHOLDER}' \\`,
    `  -H 'Content-Type: application/json' \\`,
    `  -d '${sampleBody}'`,
  ].join('\n');

  return (
    <section className="rounded-lg border border-gray-200 bg-white p-6">
      <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500">
        API spec
      </h2>
      <p className="mt-1 text-sm text-gray-500">
        วิธีเรียกจากระบบภายนอก (Zoho, Make, n8n, ฯลฯ) — แทน{' '}
        <code className="rounded bg-gray-100 px-1">{API_KEY_PLACEHOLDER}</code>{' '}
        ด้วย secret ที่ WidelyNext แจ้ง
      </p>

      <dl className="mt-4 grid grid-cols-[max-content_1fr] gap-x-4 gap-y-2 text-sm">
        <dt className="font-medium text-gray-700">Endpoint</dt>
        <dd className="font-mono text-xs">
          POST {PUBLIC_BASE_URL}/api/print/jobs
        </dd>

        <dt className="font-medium text-gray-700">Headers</dt>
        <dd className="font-mono text-xs">
          x-api-key: {API_KEY_PLACEHOLDER}
          <br />
          Content-Type: application/json
        </dd>

        <dt className="self-start pt-1 font-medium text-gray-700">Body</dt>
        <dd>
          <pre className="overflow-x-auto rounded bg-gray-50 p-3 font-mono text-xs leading-5">
{sampleBody}
          </pre>
          <ul className="mt-2 space-y-1 text-xs text-gray-500">
            <li>
              <code className="rounded bg-gray-100 px-1">printerId</code>{' '}
              <span className="text-red-500">required</span> — UUID จากตาราง
              printer ในระบบ
            </li>
            <li>
              <code className="rounded bg-gray-100 px-1">referenceId</code>{' '}
              optional — รหัสอ้างอิงฝั่งคุณ ส่งซ้ำได้ (ไม่ dedup)
            </li>
            <li>
              <code className="rounded bg-gray-100 px-1">markup</code>{' '}
              <span className="text-red-500">required</span> — Star Document
              Markup
            </li>
          </ul>
        </dd>

        <dt className="self-start pt-1 font-medium text-gray-700">Response</dt>
        <dd>
          <pre className="overflow-x-auto rounded bg-gray-50 p-3 font-mono text-xs leading-5">
{RESPONSE_EXAMPLE}
          </pre>
        </dd>

        <dt className="self-start pt-1 font-medium text-gray-700">cURL</dt>
        <dd>
          <pre className="overflow-x-auto rounded bg-gray-50 p-3 font-mono text-xs leading-5">
{curl}
          </pre>
        </dd>
      </dl>

      <p className="mt-4 text-xs text-gray-500">
        เอกสารฉบับเต็ม: ดู{' '}
        <code className="rounded bg-gray-100 px-1">_documents/API.md</code>
      </p>
    </section>
  );
}
